### ISSUE TITLE
Chests Lose Their Cached Loot Table When Un-Loaded

### ISSUE THREAD

**Issue by The-Architects727** [ArkoSammy12/loot-refill#2]
Ok so i am running into an issue with this mod where after a server restart, ALL chests do not refill at all. If i manually add the loot table to the chest then it refills fine, but on a restart it stops again.
I am running it on version 1.21, and there are other mods, but even the vanilla structures are not refiling.

**Comment by The-Architects727** [comment]
Ok a correction. It is not just when the server restarts, it is actually whenever they are unloaded. from a player that is loading them leaving the game or leaving the area.

**Comment by The-Architects727** [comment]
I have tested the mod on its own, in minecraft version 1.21 fabric and this is the issue i am running into.

https://github.com/user-attachments/assets/f957cbef-af7f-4b70-9c57-ab0c524ea40f

This is the error message that i get on the server end:
`
[13:21:02] [Server thread/ERROR]: Failed to load data for block entity minecraft:chest
--
638 | net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: ResourceKey[minecraft:loot_table / minecraft:chests/stronghold_corridor]
639 | at net.minecraft.class_2960.method_45135(class_2960.java:270) ~[client-intermediary.jar:?]
640 | at net.minecraft.class_2960.method_60936(class_2960.java:48) ~[client-intermediary.jar:?]
641 | at net.minecraft.class_2960.method_12838(class_2960.java:82) ~[client-intermediary.jar:?]
642 | at net.minecraft.class_2960.method_60654(class_2960.java:56) ~[client-intermediary.jar:?]
643 | at net.minecraft.class_2621.lootrefill$readDataFromNbt(class_2621.java:623) ~[client-intermediary.jar:?]
644 | at net.minecraft.class_8934.handler$zne000$lootrefill$readCustomDataFromNbt(class_8934.java:533) ~[client-intermediary.jar:?]
645 | at net.minecraft.class_8934.method_54871(class_8934.java:65) ~[client-intermediary.jar:?]
646 | at net.minecraft.class_2595.method_11014(class_2595.java:82) ~[client-intermediary.jar:?]
647 | at net.minecraft.class_2586.method_58690(class_2586.java:75) ~[client-intermediary.jar:?]
648 | at net.minecraft.class_2586.method_17897(class_2586.java:183) ~[client-intermediary.jar:?]
649 | at java.base/java.util.Optional.map(Unknown Source) ~[?:?]
650 | at net.minecraft.class_2586.method_11005(class_2586.java:181) ~[client-intermediary.jar:?]
651 | at net.minecraft.class_2852.method_39797(class_2852.java:411) ~[client-intermediary.jar:?]
652 | at net.minecraft.class_2818.method_12206(class_2818.java:463) ~[client-intermediary.jar:?]
653 | at net.minecraft.class_9310.method_60553(class_9310.java:147) ~[client-intermediary.jar:?]
654 | at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
655 | at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
656 | at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
657 | at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:552) ~[client-intermediary.jar:?]
658 | at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
659 | at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:561) ~[client-intermediary.jar:?]
660 | at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[client-intermediary.jar:?]
661 | at net.minecraft.class_3215$class_4212.method_18857(class_3215.java:525) ~[client-intermediary.jar:?]
662 | at net.minecraft.class_3215.method_12121(class_3215.java:137) ~[client-intermediary.jar:?]
663 | at net.minecraft.class_1937.method_8402(class_1937.java:208) ~[client-intermediary.jar:?]
664 | at net.minecraft.class_4538.method_22342(class_4538.java:156) ~[client-intermediary.jar:?]
665 | at net.minecraft.class_1937.method_8497(class_1937.java:202) ~[client-intermediary.jar:?]
666 | at net.minecraft.class_1937.method_8320(class_1937.java:374) ~[client-intermediary.jar:?]
667 | at net.minecraft.class_1297.method_5852(class_1297.java:1188) ~[client-intermediary.jar:?]
668 | at net.minecraft.class_1297.method_36974(class_1297.java:866) ~[client-intermediary.jar:?]
669 | at net.minecraft.class_1297.method_5784(class_1297.java:814) ~[client-intermediary.jar:?]
670 | at net.minecraft.class_3244.method_12063(class_3244.java:959) ~[client-intermediary.jar:?]
671 | at net.minecraft.class_2828.method_12272(class_2828.java:142) ~[client-intermediary.jar:?]
672 | at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:18) ~[client-intermediary.jar:?]
673 | at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[client-intermediary.jar:?]
674 | at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
675 | at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
676 | at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
677 | at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[client-intermediary.jar:?]
678 | at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[client-intermediary.jar:?]
679 | at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
680 | at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[client-intermediary.jar:?]
681 | at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[client-intermediary.jar:?]
682 | at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[client-intermediary.jar:?]
683 | at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[client-intermediary.jar:?]
684 | at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[client-intermediary.jar:?]
685 | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[client-intermediary.jar:?]
686 | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
687 | at java.base/java.lang.Thread.run(Unknown Source) [?:?]
688 | [13:21:02] [Server thread/WARN]: Skipping BlockEntity with id minecraft:chest
`

**Comment by KingsHakiUser** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by The-Architects727** [comment]
> NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

What happened? Did you find the issue?

**Comment by ArkoSammy12** [comment]
Hello @The-Architects727 . I've recently decided to revisit this mod. This issue should hopefully be fixed as per the latest commits, but I won't yet close the issue until I've confirmed the issue is gone. Thanks for reporting.

From what I can tell from the clip and the stacktrace, it seems like some whitespace characters get inserted between the slash `/` which causes the loot table key to fail to be read properly. Not exactly sure how that happens but from the clip I can tell that it happens before you unload the chest and after the chest is filled for the first time by the vanilla game, which suggests an issue with saving the loot table registry key instead of the chest being unloaded.

**Comment by ArkoSammy12** [comment]
I can confirm this issue no longer happens as of the latest commit. Thanks again for reporting 👍🏻
